change new study user from TextField to AutoComplete field
ABC-TransitionBasCarbone/bilan-carbone pull request #105
Opened 2024-11-13 13:42 UTC by fortinlouis

#102
Ajout d'un auto-complete
message d'avertissement si l'utilisateur n'est pas dans l'organisation ou n'a pas de compte

2024-11-13 14:41 UTC, desoindx requested changes

2024-11-13 14:41 UTC, desoindx commented on src/app/(dashboard)/etudes/[id]/droits/ajouter/page.tsx
> +  const userEmails = users.filter((user) => !existingUsers.includes(user.email)).map((user) => user.email)
c'est la responsabilité du composant d'en dessous de faire ca

2024-11-13 14:41 UTC, desoindx commented on src/components/form/Autocomplete.tsx
> +  freeSolo = false,
pas utile, c'est automatiquement passé avec les autocompleteProps

2024-11-13 14:41 UTC, desoindx commented on src/components/study/rights/NewStudyRightForm.module.css
> +}
tu peux pas utliser le helper du textField ?

2024-11-13 14:41 UTC, desoindx commented on src/components/study/rights/NewStudyRightForm.tsx
> +    form.setValue('email', value || '')
je pense pas qu'il y ait besoin de trigger le setValue ici, tu peux juste faire le check et setter le warning ?

2024-11-13 14:41 UTC, desoindx commented on src/components/study/rights/NewStudyRightForm.tsx
> +  const [externalWarning, setExternalWarning] = useState(false)
on peut trouver un meilleur nom ?

2024-11-13 15:37 UTC, fortinlouis commented on src/components/study/rights/NewStudyRightForm.tsx
> +    form.setValue('email', value || '')
Justement si. Sinon ça ne se valide pas lorsque l'on tape du texte (c'est ça qui avait fait planter la ci lors de mon 1er push)

2024-11-13 16:07 UTC, desoindx commented on src/components/study/rights/NewStudyRightForm.tsx
> +    form.setValue('email', value || '')
mais justement, tu nas pas besoin que ca valide le text dans le form, tu veux juste checker ce qui se passe

2024-11-14 08:05 UTC, fortinlouis commented on src/components/study/rights/NewStudyRightForm.tsx
> +    form.setValue('email', value || '')
Je me suis mal exprimé. Si on ne fait pas ce setValue, lorsque l'on tape à la main toute l'adresse, le champs "email" ne se met jamais à jour. Donc on en a besoin, sinon il n'y a que la sélection de la valeur via le autocomplete qui fonctionne

2024-11-14 15:49 UTC, desoindx requested changes

2024-11-14 15:49 UTC, desoindx commented on src/components/form/Autocomplete.tsx
> +  onChangedValue?: (value: string | null) => void
toujours pas utile c'est dans les props de l'autocomplete

2024-11-14 15:49 UTC, desoindx commented on src/components/study/rights/NewStudyRightForm.tsx
> +  const checkExternal = (value: string | null) => {
```suggestion
  const checkIUserIsExternalUser = (value: string | null) => {
```
et je pense pas que ce soit une fonction utile, tu peux l'inliner (ou alors la mettre dans un useCallback

2024-11-14 15:49 UTC, desoindx commented on src/components/study/rights/NewStudyRightForm.tsx
> +    if (validEmail.success && value && !usersEmail.includes(value)) {
tu as besoin du check de value la ? vu que l'email est obligatoire ca devrait jamais arriver

2024-11-14 15:57 UTC, fortinlouis commented on src/components/form/Autocomplete.tsx
> +  onChangedValue?: (value: string | null) => void
onInputChange existe, mais pas onChangedValue
Et la fonction prend 3 arguments (event: SyntheticEvent, value: string, reason: AutocompleteInputChangeReason) => void, ce qui rend la chose moins lisible

2024-11-14 16:02 UTC, desoindx commented on src/components/form/Autocomplete.tsx
> +  onChangedValue?: (value: string | null) => void
si elle a 3 arguments c'est qu'il y a une raison, la tu fais un comportement forcé sur la base d'un exemple

2024-11-14 16:03 UTC, desoindx reviewed
tu as enleve le test du check du warning ?

2024-11-14 16:08 UTC, desoindx commented on src/components/study/rights/NewStudyRightForm.tsx
> +    if (validEmail.success && value && !usersEmail.includes(value)) {
parceque tu utilises la value n'est pas fortement typé en fonction du success
utilises validEmail.data

2024-11-14 16:31 UTC, fortinlouis commented
> tu as enleve le test du check du warning ?

Oui, je n'ai plus le data-testid pour le récupérer, et n'ai pas trouvé dans la doc. J'en ai ajouté un dans le helperText

2024-11-14 17:10 UTC, desoindx requested changes

2024-11-14 17:10 UTC, desoindx commented on src/components/form/Autocomplete.tsx
> +  freeSolo?: boolean
Toujours inutile

2024-11-14 17:43 UTC, desoindx approved these changes

2024-11-14 17:44 UTC, merged