Feat/41 fe history
ABC-TransitionBasCarbone/bilan-carbone pull request #137
Opened 2024-11-19 16:28 UTC by fortinlouis

- Ajout de la table version (id, name, source ( = BaseCarbone), createdAt
- Ajout de versionId aux table emission_factor et study
- Ajout d'une option lors de l'import des FE pour supprimer vider les tables concernées

2024-11-19 17:49 UTC, desoindx requested changes

2024-11-19 17:49 UTC, desoindx commented on prisma/schema/emissionFactor.prisma
> +enum EmissionSource {
On a deja une enum pour ca
et des sources d'emission c'est autre chose !

2024-11-19 17:49 UTC, desoindx commented on prisma/schema/emissionFactor.prisma
> +  name      String
on a dit qu'on avait un name a nous et un id a eux

2024-11-19 17:49 UTC, desoindx commented on prisma/schema/study.prisma
> +  versionId String?                @map("version_id")
Obligatoire non ?

2024-11-19 17:49 UTC, desoindx commented on prisma/schema/emissionFactor.prisma
> +model EmissionFactorVersion {
```suggestion
model EmissionFactorImportVersion {
```

2024-11-19 17:49 UTC, desoindx commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +  if (params.reset) {
je comprends pas l'interet de ce reset ?

2024-11-19 17:49 UTC, desoindx commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +      prismaClient.emissionFactorPartMetaData.deleteMany(),
tu as tester ca ? j'ai du mal a voir comment ca peut marcher si tu as deja des emissionssources qui les utilisent

2024-11-19 17:49 UTC, desoindx commented on src/services/serverFunctions/study.ts
> +  const activeVersion = await prismaClient.emissionFactorVersion.findFirst({
normalement c'est toujours defini

2024-11-20 09:04 UTC, cmolle commented on prisma/schema/emissionFactor.prisma
> +  name      String
D'apres le ticket on avait dit qu'on gardait le nom du fichier également

2024-11-20 09:06 UTC, cmolle commented on prisma/schema/emissionFactor.prisma
> +  name      String
D'ailleurs dans le ticket on avait pas mis la source mais ca me parait une bonne idée de la rajouter ! Même si je rejoins Xavier sur le fait que EmissionSource existe déjà et correspond à autre chose. On pourrait nommer ca EmissionFactorSource ? ou origin pour que ce soit moins confusant ?

2024-11-20 09:06 UTC, cmolle commented on prisma/seed.ts
> +    data: { source: EmissionSource.BaseCarbone, name: '1' },
A quoi sert le name ?

2024-11-20 09:07 UTC, cmolle commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +  const version = results.data.description.split('®')[1].split('V')[1].split('\n')[0]
Est-ce que dans l'api on peut préciser la version qu'on veut ou on récupère forcément la dernière ?

2024-11-20 09:09 UTC, cmolle commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +  if (params.reset) {
Je trouve un peu dangereux de pouvoir supprimer toutes les études avec juste le paramètre reset ... Est-ce qu'il ne faudrait pas un processus pour valider qu'on ne le fasse jamais en prod ?

2024-11-20 10:06 UTC, fortinlouis commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +  if (params.reset) {
Le nouveau comportement "normal" c'est d'ajouter les FE à ceux qui existent (avec check sur la version). J'ai ajouté cette option pour avoir l'opportunité, en tant que dev à vider la bdd et repartir sur une liste vierge

2024-11-20 10:08 UTC, fortinlouis commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +  const version = results.data.description.split('®')[1].split('V')[1].split('\n')[0]
Pour moi, on ne récupère que la dernière en date

2024-11-20 10:09 UTC, desoindx commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +  if (params.reset) {
dans quel cas tu penses en avoir besoin ?

2024-11-20 10:32 UTC, cmolle commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +  const version = results.data.description.split('®')[1].split('V')[1].split('\n')[0]
A choisir je me dis qu'il vaut peut être mieux se baser sur le nom du fichier plutôt que sur la description, qu'en penses-tu ?

2024-11-20 10:32 UTC, cmolle commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +  const version = results.data.description.split('®')[1].split('V')[1].split('\n')[0]
Ou sinon on fait un prompt et il faudra qu'on fasse attention à rentrer le bon numéro de version 🤔

2024-11-20 14:14 UTC, fortinlouis commented on prisma/seed.ts
> +    data: { source: EmissionSource.BaseCarbone, name: '1' },
C'est le 'numéro de version' (23.4 dans notre cas réel)

2024-11-20 14:16 UTC, fortinlouis commented on prisma/schema/emissionFactor.prisma
> +enum EmissionSource {
J'avoue que j'ai été en panne d'inspiration pour le nom. `EmissionFactorImportSource` ?

2024-11-20 14:19 UTC, fortinlouis commented on prisma/schema/emissionFactor.prisma
> +  name      String
J'ai bien repris les infos du ticket et qui correspondent à mes souvenirs :
- `id`
- `source` (BaseCarbone) (changer le nom ?)
- `name`(23.4)
- `date`

2024-11-20 14:23 UTC, fortinlouis commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +  if (params.reset) {
J'ai pas d'exemples particulier non. J'ai voulu nous donner  l'opportunité de garder le comportement actuel. Après, c'est vrai qu'à partir du moment où on a l'historisation, on ne veut à priori plus reset. Et il reste la seed pour ça

2024-11-20 14:24 UTC, fortinlouis commented on src/services/serverFunctions/study.ts
> +  const activeVersion = await prismaClient.emissionFactorVersion.findFirst({
Comment ça ?

2024-11-20 14:34 UTC, desoindx commented on prisma/schema/emissionFactor.prisma
> +enum EmissionSource {
Non, on a déjà le imported from dans les fe qui correspond à ça pas besoin d'en créer une nouvelle

2024-11-20 14:35 UTC, desoindx commented on prisma/schema/emissionFactor.prisma
> +  name      String
On avait aussi mis un id interne
Name => 23.4, à rentrer nous même lors de l'impôt
Idinterne => le nom de fichier inintelligible qui nous assure l'unicité

2024-11-21 09:38 UTC, desoindx commented on src/services/serverFunctions/study.ts
> +  const activeVersion = await prismaClient.emissionFactorVersion.findFirst({
dans ce cas la throw une erreur, qu'on ait un avertissement propre

2024-11-21 09:41 UTC, desoindx requested changes

2024-11-21 09:41 UTC, desoindx commented on prisma/schema/emissionFactor.prisma
> +  idInterne String   @map("id_interne") @unique
pas tres anglais ce nom

2024-11-21 09:41 UTC, desoindx commented on prisma/schema/emissionFactor.prisma
> +  idInterne String   @map("id_interne") @unique
et pas forcement unique, c'est le couple idInterne/source qui est unique

2024-11-21 09:41 UTC, desoindx commented on src/services/serverFunctions/study.ts
> +import { auth } from '../auth'
Tu as un truc bizarre dans ta config qui change ca a chaque fois. Il faut le fixer

2024-11-21 10:46 UTC, desoindx approved these changes

2024-11-21 11:21 UTC, merged