add an emission factors import option on seed script
ABC-TransitionBasCarbone/bilan-carbone pull request #140
Opened 2024-11-19 17:47 UTC by fortinlouis

#121 ajout de la possibilité d'importer les FE pendant le seed :
`npx prisma db seed -- -i`

2024-11-20 07:52 UTC, desoindx requested changes

2024-11-20 07:52 UTC, desoindx commented on prisma/seed.ts
> +  if (!!params.importFactors) {
pq la double negation ici ?

2024-11-20 07:52 UTC, desoindx commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +if (require.main === module) {
Ca serait nice d'avoir le code dans un code commun pour les appeler dans les deux et eviter ce genre de code criptique

2024-11-20 07:53 UTC, desoindx commented
> #121 ajout de la possibilité d'importer les FE pendant le seed : `npx prisma db seed -- -i`

Tu peux le rajouter dans le package json ?

2024-11-21 11:03 UTC, fortinlouis commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +if (require.main === module) {
J'ai exporté le code dans un fichier séparé, et ai ajouté un fichier index.ts qui est le script, et qui importe le code depuis getEmissionFactors

2024-11-21 11:20 UTC, desoindx commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +if (require.main === module) {
attention, le fichier getEmissionFactors n'est plus un scripts du coup donc il n'a plus rien a faire la (et c'est plus une fonction main)
et je suis pas fan de naming index => on pourra avoir d'autres script lié a la baseEmpreinte

2024-11-21 11:24 UTC, fortinlouis commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +if (require.main === module) {
- index -> getEmissionFactors
 - getEmissionFactors -> getEmissionFactorsMain
 
 ?

2024-11-21 11:39 UTC, desoindx commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +if (require.main === module) {
yes pour l'index, le code de l'autre je le mettrai bien dans services/baseEmpreinte

2024-11-21 12:25 UTC, desoindx approved these changes

2024-11-21 12:56 UTC, merged