Feat/103 cr welcome page
ABC-TransitionBasCarbone/bilan-carbone pull request #145
Opened 2024-11-21 15:46 UTC by fortinlouis

#103 
- Changement de la page d'accueil pour les utilisateurs CR
- Ajout d'une organisation enfant de l'organisation de l'utilisateur
- Modification de la page organisation

2024-11-21 16:30 UTC, desoindx requested changes

2024-11-21 16:30 UTC, desoindx commented on src/app/(dashboard)/organisations/creer/page.tsx
> +    return null
```suggestion
    return <NotFound />
```

2024-11-21 16:30 UTC, desoindx commented on src/components/pages/Organization.tsx
> +            <Studies user={user} orgnizationId={organizations[0].id} />
```suggestion
            <Studies user={user} organizationId={organizations[0].id} />
```

2024-11-21 16:30 UTC, desoindx commented on src/components/study/Studies.tsx
> +  const getStudies = orgnizationId
pq le faire en deux fois ?

2024-11-21 16:30 UTC, desoindx commented on src/db/organization.ts
> +    include: { childs: true, sites: { select: { name: true, etp: true, ca: true, id: true } } },
besoin des enfants ici ?

2024-11-21 16:30 UTC, desoindx commented on src/services/serverFunctions/organization.ts
> +    const createdOrganization = await createOrganization(organization)
il y a pas de droits sur qui peut creer une organization ??

2024-11-21 17:20 UTC, fortinlouis commented on src/services/serverFunctions/organization.ts
> +    const createdOrganization = await createOrganization(organization)
Ça n'était pas précisé dans le ticket, ni aucun autre. J'ai créé une fonction qu'il faudra probablement enrichir

2024-11-21 17:34 UTC, desoindx commented on src/services/serverFunctions/organization.ts
> +    const createdOrganization = await createOrganization(organization)
dans ce cas la crée un followup ticket aussi

2024-11-21 17:39 UTC, fortinlouis commented on src/services/serverFunctions/organization.ts
> +    const createdOrganization = await createOrganization(organization)
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/147

2024-11-22 07:58 UTC, desoindx approved these changes

2024-11-22 08:04 UTC, merged