Update infography poste
ABC-TransitionBasCarbone/bilan-carbone pull request #162
Opened 2024-11-27 14:37 UTC by cmolle

Le design est encore en cours de discussion avec Gabriel

2024-11-27 16:42 UTC, desoindx commented on eslint.config.mjs
> -      curly: 'error',
j'aime plutot bien cette regle

2024-11-27 16:42 UTC, desoindx commented on src/components/study/infography/AllPostsInfography.tsx
> +  useEffect(() => {
pq ne pas le faire coté serveur ?

2024-11-27 16:42 UTC, desoindx commented on src/components/study/infography/PostHeader.module.css
> +  flex-direction: column;
pas utile

2024-11-27 16:42 UTC, desoindx commented on src/components/study/infography/PostHeader.module.css
> +  display: flex;
tu peux utiliser flex-cc ?

2024-11-27 16:42 UTC, desoindx commented on src/components/study/infography/PostInfography.tsx
> +  const [hoverEnterTimeout, setHoverEnterTimeout] = useState<NodeJS.Timeout | null>(null)
utiliser des refs plutot ?

2024-11-27 17:07 UTC, desoindx requested changes

2024-11-27 17:07 UTC, desoindx commented on src/components/study/infography/PostInfography.module.css
> +  width: 250px;
c'est possible de le mettre en rem ?

2024-11-27 17:07 UTC, desoindx commented on src/components/study/infography/PostInfography.tsx
> +        onMouseEnter={() => {
ca serait peut etre plus simple avec une taille fixe et une transition sur le visibility hidden non ?

2024-11-27 17:07 UTC, desoindx commented on src/components/study/infography/PostInfography.tsx
> +        style={{
tu peux utiliser une classnames dynamiques ? styles[dark] ?

2024-11-27 17:07 UTC, desoindx commented on src/services/results.ts
> +export const computeResultsByPost = async (study: FullStudy) => {
pq c'est du server ca ? ca devrait etre synchrone et coté client

2024-11-28 10:22 UTC, cmolle commented on eslint.config.mjs
> -      curly: 'error',
Je trouve ca plus lisible quand il y a des mini condition de pouvoir le faire sur une ligne. Pour le coup c'est hyper subjectif mais comme j'avais un cas dans ma pr je voulais la proposer

2024-11-28 10:24 UTC, cmolle commented on src/components/study/infography/AllPostsInfography.tsx
> +  useEffect(() => {
Je vais tester, je pense que j'ai juste pas l'habitude et que du coup j'ai utilisé mes vieux réflexes

2024-11-28 10:33 UTC, cmolle commented on src/components/study/infography/PostHeader.module.css
> +  flex-direction: column;
J'ai utilisé flex-col du coup mais j'ai quand meme besoin de ce style

2024-11-28 10:33 UTC, cmolle commented on src/components/study/infography/PostInfography.tsx
> +  const [hoverEnterTimeout, setHoverEnterTimeout] = useState<NodeJS.Timeout | null>(null)
Je te laisse voir cet aprem du coup si tu trouves plus simple :)

2024-11-28 10:33 UTC, cmolle commented on src/components/study/infography/PostInfography.tsx
> +        onMouseEnter={() => {
idem

2024-11-28 10:34 UTC, cmolle commented on src/components/study/infography/PostInfography.tsx
> +        style={{
C'est possible avec les pourcentages ?

2024-11-28 10:35 UTC, cmolle commented on src/services/results.ts
> +export const computeResultsByPost = async (study: FullStudy) => {
Je ne savais pas bien comment gérer la traduction, j'ai l'impression qu'on a le choix entre côté serveur ou dans un hook react. Je savais pas ce qui était le mieux et je trouvais la partie serveur plus lisible (ca évite d'exporter une méthode dans un objet à utiliser)

2024-11-28 11:06 UTC, desoindx commented on src/components/study/infography/PostInfography.tsx
> +        style={{
yes, je peux regarder avec le hover si tu veux

2024-11-28 11:07 UTC, desoindx commented on src/services/results.ts
> +export const computeResultsByPost = async (study: FullStudy) => {
yes, mais ca fait un AR avec le serveur (qui prend du temps et du traffic) pour rien

2024-11-28 15:57 UTC, cmolle commented on src/components/study/infography/AllPostsInfography.tsx
> +  const data = useMemo(() => computeResultsByPost(study, tPost), [study, tPost])
On peut utiliser useMemo dans un composant cote serveur ? je croyais que les hooks étaient forcément cote client ? (ou alors c'est implicite ?

2024-11-28 15:59 UTC, cmolle commented on src/components/study/infography/PostInfography.tsx
> +    return Math.max(percent - 2, 0)
Du coup on peut mettre percent directement

2024-11-28 16:01 UTC, cmolle commented on src/components/study/infography/PostInfography.tsx
> +          background: `linear-gradient(to right, ${colors[postColor].dark} 0%, ${colors[postColor].dark} ${colorPercentage}%, ${colors[postColor].light} ${colorPercentage}%, ${colors[postColor].light
C'est pas bien de multiplier les useMemo ? J'avais défini des dark et litght pour que cette ligne soit un peu plus lisible

2024-11-28 16:25 UTC, desoindx commented on src/components/study/infography/AllPostsInfography.tsx
> +  const data = useMemo(() => computeResultsByPost(study, tPost), [study, tPost])
c'est executé coté client

2024-12-02 10:53 UTC, cmolle commented on src/components/study/infography/AllPostsInfography.tsx
> +  const data = useMemo(() => computeResultsByPost(study, tPost), [study, tPost])
Le useMemo ou ce composant ?

2024-12-02 11:14 UTC, desoindx commented on src/components/study/infography/AllPostsInfography.tsx
> +  const data = useMemo(() => computeResultsByPost(study, tPost), [study, tPost])
ce composant, vu qu'il est imbriqué dans d'autres composant client
(et le usememo aussi du coup)

2024-12-03 09:27 UTC, merged