Feat/165 results graphs
ABC-TransitionBasCarbone/bilan-carbone pull request #175
Opened 2024-11-29 15:29 UTC by fortinlouis

#165 

Pas de téchargement de l'étude globale dans la Box "Résultats par postes" car le bouton est au dessus, à côté du nom de l'étude (à discuter si on veut le déplacer)

2024-11-29 18:08 UTC, desoindx requested changes

2024-11-29 18:08 UTC, desoindx commented on src/components/study/results/Result.tsx
> +  const [post, setPost] = useState<Post>(Object.keys(subPostsByPost)[0] as Post)
tres chelou cette intialisation ?

2024-11-29 18:08 UTC, desoindx commented on src/components/study/results/Result.tsx
> +  const selectorOptions: Post[] = useMemo(() => (isPost ? [] : (Object.keys(subPostsByPost) as Post[])), [post])
```suggestion
  const selectorOptions: Post[] = useMemo(() => (isPost ? [] : (Object.values(Post)), [post])
```

2024-11-29 18:08 UTC, desoindx commented on src/components/study/results/Result.tsx
> +  const sort = (arr: string[]) => arr.sort((a, b) => a.length - b.length)
a sortir du composant

2024-11-29 18:08 UTC, desoindx commented on src/components/study/results/Result.tsx
> +  const sort = (arr: string[]) => arr.sort((a, b) => a.length - b.length)
et pq sorter par taille de texte ?

2024-11-29 18:08 UTC, desoindx commented on src/components/study/results/Result.tsx
> +              (emissionFactor) => emissionFactor.id === emissionSource.emissionFactor?.id,
on a deja des methodes pour calculer tout ca, cf pr de Chloé

2024-11-29 18:08 UTC, desoindx commented on src/components/study/results/Result.tsx
> +        // TODO : add css class to properly use color
pq c'est encore en todo ?

2024-11-29 18:08 UTC, desoindx commented on src/db/study.ts
> +  return study ? getStudyById(study.id) : null
chelou de refaire un get ici... pq ?

2024-11-30 07:36 UTC, desoindx commented
On s'etait pas mis d'accord pour utiliser chartjs ?

2024-12-02 07:44 UTC, fortinlouis commented on src/components/study/results/Result.tsx
> +  const sort = (arr: string[]) => arr.sort((a, b) => a.length - b.length)
J'ai fait le tri par taille car j'affiche le nom des postes/sous-postes en incliné, afin que ça rentre dans la place allouée. Le résultat, c'est que si la première colonne a un nom trop grand, elle dépasse largement à gauche et sort du cadre. C'est visuellement plus joli en triant par taille de texte

2024-12-02 11:57 UTC, fortinlouis commented on src/db/study.ts
> +  return study ? getStudyById(study.id) : null
J'ai pas trouvé de meilleure solution pour que cette fonction renvoit une FullStudy. Du coup j'ai trouvé ça assez pertinent de récupérer l'id (uniquement) de l'étude principale, puis on renvoit l'étude complète à partir de cet id.

Ça permet que FullStudy soit utilisable partout et que la logique soit centralisée dans la fonction getStudyById

2024-12-02 12:13 UTC, desoindx commented on src/db/study.ts
> +  return study ? getStudyById(study.id) : null
mais c'est affreux niveau perf :/

2024-12-02 15:19 UTC, fortinlouis commented on src/components/study/results/Result.tsx
> +  const [post, setPost] = useState<Post>(Object.keys(subPostsByPost)[0] as Post)
Comment ça ? J'ai pris la 1ère valeur de la liste des options

2024-12-02 15:22 UTC, desoindx commented on src/components/study/results/Result.tsx
> +  const [post, setPost] = useState<Post>(Object.keys(subPostsByPost)[0] as Post)
pq tu mets pas un post directement ?

2024-12-02 16:25 UTC, fortinlouis commented on src/components/study/results/Result.tsx
> +  const [post, setPost] = useState<Post>(Object.keys(subPostsByPost)[0] as Post)
Parce que si demain la liste de postes change, il faudra changer la valeur initiale du selecteur. Sauf poste plus important que les autres, il est plus pérein d'utiliser la première valeur de la liste (que j'ai changé pour `Object.values(Post)[0]`, suivant ta suggestion pour les valeurs de la liste

2024-12-03 11:39 UTC, desoindx requested changes

2024-12-03 11:39 UTC, desoindx commented on src/db/study.ts
> +export type FullStudy = Exclude<AsyncReturnType<typeof getStudyById | typeof getMainStudy>, null>
pq tu rajoutes le | ici ? C'est censé renvoyé le même type, sinon il y a un probleme

2024-12-03 11:39 UTC, desoindx commented on src/i18n/en.json
> +    "loading": "Loading...",
pas utilisé

2024-12-03 11:39 UTC, desoindx commented on src/i18n/en.json
> +    "noData": "No data to display"
pareil

2024-12-03 13:39 UTC, fortinlouis commented on src/components/study/results/Result.tsx
> +      const subPosts = computedResults.find((emissionPost) => emissionPost.post === post)?.subPosts || []
le linter me dit que non. J'ai essayé de corriger le type ResultsByPost, mais ça ne change rien

2024-12-03 13:41 UTC, fortinlouis commented on src/components/study/results/Result.tsx
> +      if (data.every((totalEmissions) => totalEmissions === 0)) {
Non, ça renvoit tous les résultats qui ont des sources d'emissions. Même celles qui ont value = 0

2024-12-03 13:54 UTC, fortinlouis commented on src/components/study/results/Result.tsx
> +  const dynamicHeight = useMemo(() => Math.min(dynamicMargin.bottom * 3, 500), [dynamicMargin])
On est obligé d'avoir des graphs de taille différentes : La hauteur inclus les labels de l'axe X, donc selon la longueur des labels, ils seront inclinés et prendront +/- de place

2024-12-03 14:38 UTC, desoindx commented on src/components/study/results/Result.tsx
> +      if (data.every((totalEmissions) => totalEmissions === 0)) {
@cmolle c'est toi qui a changé cette fonctionnalité ?
je l'ai presente pendant la demo donc sur que ca fonctionnait comme ca et que c'est le besoin

2024-12-03 14:38 UTC, desoindx commented on src/components/study/results/Result.tsx
> +  const dynamicHeight = useMemo(() => Math.min(dynamicMargin.bottom * 3, 500), [dynamicMargin])
non on est pas oblgé, tu peux donner une hauteur fixe + une variable selon les labels

2024-12-03 15:09 UTC, cmolle commented on src/components/study/results/Result.tsx
> +      if (data.every((totalEmissions) => totalEmissions === 0)) {
Oui c'est moi qui est changé, je suis passée de : on garde que ceux qui ont une valeur plus grande que 0 à on garde que ceux qui ont au moins une source d'émission. 
Je suis désolée j'ai oublié de le mettre en avant dans ma PR pour proposer le changement. 
Dans l'idée je trouvais ca intéressant de ne pas afficher tous les sous postes si il y en a des non pertinents, mais je trouvais ca utile d'indiquer que certains sont à 0, ca permet à l'utilisateur de se dire "pourquoi c'est à 0 ? Ah mince on s'en est pas occupé" vs si il apparait pas il peut l'oublier. 

Je crois que y avait une autre raison mais je l'ai plus en tête. 

Après à discuter, je suis pas fermée et je comptais au départ en parler dans ma PR avant d'oublier 😅 

Et d'ailleurs j'ai pas lu la PR donc pas sûre d'être pertinente mais idem ici je me demande si c'est pas pertinent d'afficher dans les graphes ceux pour lesquels il est prévu qu'il y ait des tco2 vvu qu'il y a des sources d'émission

2024-12-03 15:21 UTC, fortinlouis commented on src/components/study/results/Result.tsx
> +      if (data.every((totalEmissions) => totalEmissions === 0)) {
Au niveau des graphs, ça me parait pertinent d'afficher même ceux qui sont à 0. Ça donne un aperçu de tous les postes/sous-postes qui sont possibles, et ça évite les retours qui pourraient être "pourquoi il manque tel ou tel élément ?"

2024-12-03 15:25 UTC, fortinlouis commented on src/db/study.ts
> +      ...FullStudyIncluder,
Parce que sans le `satisfies Prisma.StudyInclude` j'avais un problème niveau TS que je n'avais pas réussi à corriger autrement

2024-12-03 15:29 UTC, desoindx commented on src/components/study/results/Result.tsx
> +      if (data.every((totalEmissions) => totalEmissions === 0)) {
Ca devient dur a suivre tout ces changements de specs.. ca va être le bordel à harmoniser...

2024-12-04 07:56 UTC, desoindx requested changes

2024-12-04 07:56 UTC, desoindx commented on src/components/study/results/Result.tsx
> +const graphBarColor = '#346fef' // --primary-40
quand je disais utiliser un var, je parlais de var(--primary-40)

2024-12-04 07:56 UTC, desoindx commented on src/components/study/results/Result.tsx
> +  const selectorOptions = by === 'Post' ? [] : Object.values(Post)
je comprends toujours pas pq ca c'est pas juste Object.values(Post)

2024-12-04 07:56 UTC, desoindx commented on src/components/study/results/Result.tsx
> +  const dynamicHeight = useMemo(() => labelsHeight + 300 + (by === 'Post' ? 70 : 0), [yData, labelsHeight])
pareil, je comprends toujours pas l'interet de la variable labelHeight intermediaire...

2024-12-04 07:56 UTC, desoindx commented on src/components/study/results/Result.tsx
> +            labels: xAxis.map((post) => tPost(post)),
nitpick, tu peux faire la traduction directement dans le xAxis

2024-12-04 07:56 UTC, desoindx commented on src/db/study.ts
> +const FullStudyInclude = {
```suggestion
const fullStudyInclude = {
```

2024-12-04 08:28 UTC, fortinlouis commented on src/components/study/results/Result.tsx
> +            labels: xAxis.map((post) => tPost(post)),
On a besoin des valeur initiales pour yData

2024-12-04 10:21 UTC, desoindx commented on src/tests/end-to-end/app/home.cy.ts
> +    cy.getByTestId('home-actualities').scrollIntoView()
pq ?

2024-12-04 10:25 UTC, fortinlouis commented on src/tests/end-to-end/app/home.cy.ts
> +    cy.getByTestId('home-actualities').scrollIntoView()
Parce qu'avec les graphs, les actualités ne sont plus visibles sur l'écran sans scroll. C'est la même logique que pour la liste d'études ou d'organisations pour les utilisateurs CR

2024-12-04 10:37 UTC, desoindx approved these changes

2024-12-04 10:37 UTC, merged