Tech/tools https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/13
ABC-TransitionBasCarbone/bilan-carbone pull request #18
Opened 2024-10-09 14:37 UTC by fortinlouis

2024-10-09 14:45 UTC, desoindx approved these changes

2024-10-09 15:32 UTC, cmolle approved these changes

2024-10-09 16:03 UTC, cmolle commented on package.json
>  }
Est-ce que tu pourrais rajouter une ligne à la fin du fichier ? (désolée l'icone github me trigger)

2024-10-10 09:01 UTC, desoindx requested changes

2024-10-10 09:01 UTC, desoindx commented on cypress.config.ts
> +    baseUrl: 'http://localhost:3000', // URL de base pour tes tests
Commentaire inutile

2024-10-10 09:01 UTC, desoindx commented on jest.config.ts
> +  dir: './src',
le .env et le next.config.mjs ne sont pas dans ./src

2024-10-10 09:04 UTC, fortinlouis commented on .prettierignore
> +# add files or folders that should not be pretified
"insertFinalNewline": true dans le prettierrc ?

2024-10-10 13:21 UTC, merged