Do send the non existing user information on add person on study
ABC-TransitionBasCarbone/bilan-carbone pull request #204
Opened 2024-12-04 14:26 UTC by fortinlouis

#186

2024-12-04 15:44 UTC, cmolle commented on src/components/study/rights/NewStudyRightForm.tsx
> +    console.log('result', result)
A supprimer

2024-12-04 15:44 UTC, cmolle commented on src/services/serverFunctions/study.ts
> +    console.log('level : ', newUser.level)
A supprimer

2024-12-04 16:03 UTC, desoindx commented
> #186
> 
> Manque le check sur la licence (pas encore implémentée niveau organisation)
> 
> ## Propositions de changement des messages (mettre en évidence le changement de droit). Ce message n'est affiché que si le droit initialement sélectionné n'est pas lecteur :
> * readerOnly: "The person does not match the necessary conditions for this role. You will only be able to give them access to the study with READ or contribution rights. An email will be sent to them to give access to the study."
> 
> * readerOnly: "La personne ne réunit pas les conditions nécessaires pour l'ajouter avec ce rôle. Vous ne pourrez donc lui donner un accès à l'étude qu'avec les droits de LECTURE ou de contribution. Un mail lui sera envoyé pour lui donner accès à l'étude."

Est ce qu'on veut pas lui dire quand meme que l'utilisateur est hors organization ?

2024-12-04 16:17 UTC, desoindx requested changes

2024-12-04 16:17 UTC, desoindx commented on src/db/study.ts
>            organizationId: true,
en recuperant l'organisationId, on peut savoir si la personne à déjà un compte ou pas du coup :/
la faille de securité est toujours la :(

2024-12-04 16:44 UTC, fortinlouis commented
> > #186
> > Manque le check sur la licence (pas encore implémentée niveau organisation)
> > ## Propositions de changement des messages (mettre en évidence le changement de droit). Ce message n'est affiché que si le droit initialement sélectionné n'est pas lecteur :
> > 
> > * readerOnly: "The person does not match the necessary conditions for this role. You will only be able to give them access to the study with READ or contribution rights. An email will be sent to them to give access to the study."
> > * readerOnly: "La personne ne réunit pas les conditions nécessaires pour l'ajouter avec ce rôle. Vous ne pourrez donc lui donner un accès à l'étude qu'avec les droits de LECTURE ou de contribution. Un mail lui sera envoyé pour lui donner accès à l'étude."
> 
> Est ce qu'on veut pas lui dire quand meme que l'utilisateur est hors organization ?

Le but est d'en dire le moins possible

2024-12-04 16:49 UTC, fortinlouis commented on src/services/serverFunctions/study.ts
> +    return newUser.level === Level.Initial ? NewStudyRightStatus.ReaderOnly : NewStudyRightStatus.Valid
cf le ticket : "si l'utilisateur essaye d'ajouter une personne [...] qui n'a pas sa licence ou formation à jour, on ajoute un warning "[...]". Elle sera donc ajoutée avec le rôle de lecteur uniquement".

Il manque le check sur la licence, que l'on ne gère pas encore niveau orga

2024-12-04 16:51 UTC, fortinlouis commented on src/components/study/rights/SelectStudyRole.tsx
> +    (user.organizationId !== rowUser.organizationId && rowUser.level === Level.Initial)
Je fais le même test qu'à la création

2024-12-04 17:39 UTC, fortinlouis commented on src/db/study.ts
>            organizationId: true,
À discuter lors du daily dans ce cas, car on parle de l'existant

2024-12-05 08:11 UTC, desoindx commented on src/services/serverFunctions/study.ts
> +    return newUser.level === Level.Initial ? NewStudyRightStatus.ReaderOnly : NewStudyRightStatus.Valid
et c'est bien ce que je dis, ne pas avoir sa licence ou formation à jour n'a rien a voir avec le Level.Initial

2024-12-05 11:13 UTC, fortinlouis commented on src/db/study.ts
>            organizationId: true,
Du coup, est ce qu'on veut supprimer cet organizationId (quand il est différent de celui de l'utilisateur) dans tous les cas ? Ou simplement pour la page de cadrage ?

2024-12-05 16:57 UTC, desoindx requested changes

2024-12-05 16:57 UTC, desoindx commented on src/components/study/rights/SelectStudyRole.tsx
> +      (!rowUser.organizationId && !getAllowedLevels(rowUser.level).includes(studyLevel)),
je vois toujours pas le rapport avec le level ici...

2024-12-09 08:24 UTC, desoindx requested changes

2024-12-09 08:24 UTC, desoindx commented on src/db/study.ts
> +    .then((study) => {
pq un then ici ? on utilise des async await partout

2024-12-09 08:24 UTC, desoindx commented on src/components/study/rights/SelectStudyRole.tsx
> +      'readerOnly' in rowUser,
ca va planter un moment ca, c'est sur qu'on mettra un false qq part

2024-12-09 08:24 UTC, desoindx commented on src/db/study.ts
> +                  organizationId: null,
undefined plutot que null ?

2024-12-09 08:24 UTC, desoindx commented on src/db/study.ts
> +                  ...(readerOnly ? { readerOnly: true } : {}),
```suggestion
                   readerOnly: readerOnly ? true : undefined,
```

2024-12-09 08:24 UTC, desoindx commented on src/i18n/fr.json
>            "otherOrganization": "Elle est utilisatrice du BC+ au sein d'une autre organisation que la votre.",
Ce message n'est plus ok

2024-12-09 08:24 UTC, desoindx commented on src/app/(dashboard)/etudes/[id]/(contributor)/contributeur/page.tsx
> +  const study = await getStudyById(id, session.user.organizationId as string)
pq tu es obligé de le forcer as string partout ici ? ca me semble chelou...

2024-12-09 13:22 UTC, desoindx requested changes
j'ai toujorus pas l'impression que ca fait ce qui est demandé

2024-12-09 13:22 UTC, desoindx commented on src/tests/end-to-end/app/study-rights.cy.ts
> +    })
c'est quoi l'interet de ca ?

2024-12-09 14:44 UTC, fortinlouis commented on src/tests/end-to-end/app/study-rights.cy.ts
> +    })
Le but c'est de tester la gestion des droits, en l'occurrence de passer bc-admin-1@yopmail.com en éditeur plutôt que validateur, et ainsi ce dernier n'a plus le droit de changer le droit de bc-default-0@yopmail.com qui est validateur

2024-12-10 08:50 UTC, cmolle commented
> #186
> 
> Manque le check sur la licence (pas encore implémentée niveau organisation)
> ## Propositions de changement des messages (mettre en évidence le changement de droit). Ce message n'est affiché que si le droit initialement sélectionné n'est pas lecteur :
> 
>     * otherOrganization: "They are not within your organization.",
> 
>     * readerOnly: "The person does not match the necessary conditions for this role. You will only be able to give them access to the study with READ or contribution rights. An email will be sent to them to give access to the study.",
> 
> 
>     * otherOrganization: "Elle ne fait pas partie de votre organisation."
> 
>     * readerOnly: "La personne ne réunit pas les conditions nécessaires pour l'ajouter avec ce rôle. Vous ne pourrez donc lui donner un accès à l'étude qu'avec les droits de LECTURE ou de contribution. Un mail lui sera envoyé pour lui donner accès à l'étude."
> 
> 
> Scénario réalisés :
> 
>     * Ajout d'une personne avec compte, avec les droits de lecteur -> otherOrganization
> 
>     * Ajout d'une personne avec compte, avec les droits editeur/validateur mais un niveau insuffisant (user.level < study.level) -> readerOnly
> 
>     * Ajout d'une personne avec compte, avec les droits editeur/validateur avec un niveau suffisant -> otherOrganization
> 
>     * Ajout d'une personne sans compte, avec les droits de lecteur -> otherOrganization
> 
>     * Ajout d'une personne sans compte, avec les droits editeur/validateur -> readerOnly
>       @cmolle est ce que ça te parait oké ?


Pour le otherOrganization je pense qu'on peut mettre un message un peu plus long : "Cette personne ne fait pas partie de votre organisation. Êtes-vous sûre de vouloir l'ajouter à cette étude ? Elle aura accès aux données de cette étude uniquement."

Pour les 5 cas, on est d'accord que si tu mets readerOnly tu mets aussi otherOrganization ? 

D'ailleurs je me dis qu'il y a aussi le cas où la personne est bien dans l'organisation mais n'a pas un niveau suffisant de formation et dans ce cas là on peut mettre readerOnly sans otherOrganisation.

2024-12-10 09:41 UTC, fortinlouis commented
> Pour le otherOrganization je pense qu'on peut mettre un message un peu plus long : "Cette personne ne fait pas partie de votre organisation. Êtes-vous sûre de vouloir l'ajouter à cette étude ? Elle aura accès aux données de cette étude uniquement."
> 
> Pour les 5 cas, on est d'accord que si tu mets readerOnly tu mets aussi otherOrganization ?
> 
> D'ailleurs je me dis qu'il y a aussi le cas où la personne est bien dans l'organisation mais n'a pas un niveau suffisant de formation et dans ce cas là on peut mettre readerOnly sans otherOrganisation.

Il y a déjà "Êtes-vous sûr de vouloir ajouter cette personne à votre étude ?" en "header" de la modale :
![image](https://github.com/user-attachments/assets/cb0d38f7-d456-4987-8fe4-10eb7a4665f5)
![image](https://github.com/user-attachments/assets/944ef610-4e46-417a-866f-738cbae16671)

Mais donc non, quand on affiche readerOnly, on n'affiche pas le otherOrganization en plus. Il me semble que c'est toi qui m'avait spécifiquement dit de mettre ce message "La personne ne réunit pas les conditions nécessaires". Est ce que tu veux que je change pour "La personne ne fait pas partie de votre organisation et ne réunit pas les conditions nécessaires" ?

Je vois avec Gabriel pour le blocage des droits en cas de niveau insuffisant, même en faisant partie de l'organisation

2024-12-10 10:52 UTC, cmolle commented
@fortinlouis désolée du coup j'ai du m'emmêler les pinceaux, mais oui je veux bien que si la personne ne fait pas partie de l'organisation on voit toujours le message otherOrganisation. Pour moi c'est une information importante vu qu'elle donne des informations à une personne extérieur il ne faut pas que ce soit fiat à la légère. 

Pour l'autre sujet, parfait j'avais oublié le titre. On peut peut être rajouter la mention du coup que la personne aura accès uniquement aux données de cette étude pour rassurer tout de même qu'elle donne pas accès à tout l'outil

2024-12-10 10:55 UTC, fortinlouis commented
> @fortinlouis désolée du coup j'ai du m'emmêler les pinceaux, mais oui je veux bien que si la personne ne fait pas partie de l'organisation on voit toujours le message otherOrganisation. Pour moi c'est une information importante vu qu'elle donne des informations à une personne extérieur il ne faut pas que ce soit fiat à la légère.
> 
> Pour l'autre sujet, parfait j'avais oublié le titre. On peut peut être rajouter la mention du coup que la personne aura accès uniquement aux données de cette étude pour rassurer tout de même qu'elle donne pas accès à tout l'outil

Oké, je note ça.
Du coup, Gabriel a validé de son côté que les personnes, même s'ils font partie de l'organisation doivent avoir un niveau qui match celui de l'étude pour avoir un rôle autre que Lecteur. Je corrige ça aussi

2024-12-11 12:59 UTC, closed without merging