Fix/165 study graphs
ABC-TransitionBasCarbone/bilan-carbone pull request #231
Opened 2024-12-10 11:05 UTC by fortinlouis

#165 Suite aux retours de Gabriel en staging : 
- On ne veut plus afficher les émissions des sources non validées sur les graphs : Le comportement est étendu aux infographies et résultats (vu avec Chloé)
- Changement de l'ordre des postes dans les graphs
- Changement de l'étude principale : On récupère la dernière étude de l'organisation (user.organizationId pour les utilisateurs normaux, organization.id pour les page d'accueil des organisations)
- Ajout du nom de l'étude pour éviter les doutes sur l'étude affichée

2024-12-10 11:21 UTC, desoindx requested changes

2024-12-10 11:21 UTC, desoindx commented on src/db/study.ts
> +export const getMainStudy = async (user: User, organizationId: string | null) => {
pq tu te trimballes le null jusqu'ici ? autant le gerer beaucoup plus haut ?

2024-12-10 11:21 UTC, desoindx commented on src/db/study.ts
> -        { contributors: { some: { userId: user.id } } },
On ignore les droits ???

2024-12-10 11:21 UTC, desoindx commented on src/services/posts.ts
>    Immobilisations = 'Immobilisations',
C'est quoi la logique du sort sur le graph ? la tu lies une fonctionnalité front à une definition enum, rien ne nous dit que l'ordre ne va pas changer ici

2024-12-10 11:21 UTC, desoindx commented on src/services/results/consolidated.ts
> -                (!emission.value || !emission.emissionFactor ? 0 : emission.value * emission.emissionFactor.totalCo2),
Non... il faut que le validated soit dans le filter au dessus => sinon ton numberOfEmissionSource par exemple va etre faux
et il faut que tu geres ca dans l'export beges aussi

2024-12-11 13:50 UTC, fortinlouis commented on src/db/study.ts
> -        { contributors: { some: { userId: user.id } } },
Oui, c'est une demande de Gabriel : L'étude de la page d'accueil est l'étude la plus récente de ton organisation, sans se préoccuper du rôle de l'utilisateur sur cette étude

2024-12-11 14:02 UTC, fortinlouis commented on src/services/posts.ts
>    Immobilisations = 'Immobilisations',
C'est également une demande de Gabriel (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/165#issuecomment-2527807992)

Les colonnes doivent être triées comme suit: "Énergie, Autres émissions directes, Intrants - Biens et matière, Intrants - services, Déchets Directs, Fret, Déplacements, Immobilisations, Utilisation, Fin de vie"

Après discussion, il a demandé cet ordre : "Énergie, Déchets Directs, Intrants - Biens et matière, Intrants - services, Autres émissions directes, Fret, Déplacements, Immobilisations, Utilisation, Fin de vie"

Tu préfèrerais avoir une list hard-codée en mode [Post.Energies, Post.DechetsDirects, ...] ?

2024-12-11 17:52 UTC, desoindx requested changes

2024-12-11 17:52 UTC, desoindx commented on src/components/study/results/Result.tsx
> +    <div className="">
```suggestion
    <div>
```

2024-12-11 17:52 UTC, desoindx commented on src/db/study.ts
> +export const getMainStudy = async (user: User, organizationId: string | null) => {
Tu as mis un pouce en l'air, mais n'a rien changé ?

2024-12-11 17:52 UTC, desoindx commented on src/services/posts.ts
>    Immobilisations = 'Immobilisations',
yes

2024-12-11 17:52 UTC, desoindx commented on src/services/results/consolidated.ts
> -                (!emission.value || !emission.emissionFactor ? 0 : emission.value * emission.emissionFactor.totalCo2),
rien n'a changé ici non plus

2024-12-12 12:02 UTC, desoindx approved these changes

2024-12-12 12:47 UTC, merged