Feat/176 etq super administrateur je peux uploader une version csv de la base empreinte
ABC-TransitionBasCarbone/bilan-carbone pull request #235
Opened 2024-12-11 10:03 UTC by RomainCrevecoeur

## à améliorer
- [ ] accès bloqué par le middleware http://localhost:3000/admin
- [ ] L'import du fichier Excel remplit la base Postgresql
- [ ] La suite de cette PR https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/46

2024-12-12 12:32 UTC, desoindx requested changes

2024-12-12 12:32 UTC, desoindx commented on src/app/(dashboard)/admin/page.tsx
> +  }
il faut que tu rediriges vers l'accueil (ou une 404) si jamais l'utilisateur n'a pas les droits

2024-12-12 15:49 UTC, RomainCrevecoeur commented on src/app/(dashboard)/admin/page.tsx
> +  }
Je pense que c'est mieux comme ça
On peut merge non ?

2024-12-13 08:14 UTC, desoindx commented on src/app/(dashboard)/admin/page.tsx
> +  }
Il manque la question du style (un css module), et styler l'input correctement (avec un label par exemple) plutot qu'un bouton a coté (pas accessible)

2024-12-16 10:19 UTC, RomainCrevecoeur commented on src/app/(dashboard)/admin/page.tsx
> +  }
Moi j'ai copié la page profil et il n'y a pas de fichier CSS associé
Je ne vois pas ce que tu veux ajouter dans le style de l'input. 
Comme ça : https://mui.com/material-ui/react-button/#file-upload ?

2024-12-16 10:50 UTC, desoindx commented on src/app/(dashboard)/admin/page.tsx
> +  }
Yes par exemple
ou sinon juste avec un input hidden dans un label (la ce que tu fais n'est pas accessible :/)
et pour le css il n'y en a pas dans la page profile. Mais la tu mets du style directement dans ton composant ce n'est pas une bonne pratique

2024-12-16 10:53 UTC, desoindx commented on src/app/(dashboard)/admin/page.tsx
> +  }
un exemple: https://stackoverflow.com/questions/572768/styling-an-input-type-file-button

2024-12-16 14:41 UTC, RomainCrevecoeur commented on src/app/(dashboard)/admin/page.tsx
> +  }
J'ai plutôt utiliser l'input MUI
Est ce que tu peux me dire ce que tu en penses ?

2024-12-16 17:11 UTC, desoindx approved these changes

2024-12-16 17:11 UTC, desoindx commented on src/app/(dashboard)/admin/page.tsx
> +  }
je trouve le css assez complexe. Le reste c'est ce qu'il donne comme exemple donc ca me va

2024-12-17 07:46 UTC, RomainCrevecoeur commented on src/app/(dashboard)/admin/page.tsx
> +  }
J'ai simplifié normalement ça fonctionne

2024-12-17 09:03 UTC, merged