Do not send the non existing user information on add person on study
ABC-TransitionBasCarbone/bilan-carbone pull request #237
Opened 2024-12-11 11:16 UTC by fortinlouis

#186  Remplace https://github.com/ABC-TransitionBasCarbone/bilan-carbone/pull/204
Manque le check sur la licence (pas encore implémentée niveau organisation)

Propositions de changement des messages (mettre en évidence le changement de droit) :

---
- otherOrganization: "They are not within your organization.",
- readerOnly: "If they do not match the necessary conditions for this role, you will only be able to give them access to this study only with READ or contribution rights. An email will be sent to them to give access to the study.",
---
- otherOrganization: "Elle ne fait pas partie de votre organisation."
- readerOnly: "Si elle ne réunit pas les conditions nécessaires pour l'ajouter avec ce rôle, vous ne pourrez donc lui donner un accès qu'à cette étude et avec les droits de LECTURE ou de contribution. Un mail lui sera envoyé pour lui donner accès à l'étude."
---

Scénario réalisés :

- Ajout d'une personne hors organisation, avec les droits de lecteur -> otherOrganization
- Ajout d'une personne hors organisation, avec les droits editeur/validateur -> otherOrganization + readerOnly
- Ajout d'une personne membre de l'organisation, dont on sait qu'elle n'a pas le niveau pour l'étude -> on force le rôle à Lecteur et on désactive le selecteur de rôles
- Ajout d'une personne membre de l'organisation, dont on sait qu'elle a le niveau pour l'étude -> Selecteur libre
- Pour les membres hors orga, on fait le check à la création de l'étude (et on corrige éventuellement le rôle attribué). Ainsi, on ne fait aucune distinction entre les comptes et les externes, ce qui permet de ne plus donner d'indication

2024-12-11 14:04 UTC, desoindx requested changes

2024-12-11 14:31 UTC, fortinlouis commented on src/components/study/rights/NewStudyRightForm.tsx
> +    }
Ça gère le cas "NOT_AUTHORIZED"

2024-12-11 14:49 UTC, fortinlouis commented on src/db/study.ts
> +        !allowedUser.user.organizationId || !getAllowedLevels(allowedUser.user.level).includes(study.level)
Oui, car on cache le niveau de l'utilisateur quand il n'est membre de l'organisation. On ne peut donc pas faire le calcul côté front

2024-12-11 17:53 UTC, desoindx commented on src/components/study/rights/NewStudyRightForm.tsx
> +    }
il n'y a pas d'autres erreur. La personne est forcement connectée sinon elle n'arriverai pas la

2024-12-11 17:55 UTC, desoindx commented on src/db/study.ts
> +    include: { emissionSources: fullStudyInclude.emissionSources },
pour le readerOnly, c'est pour ca que je proposais de le remonter coté front. Ca evite ce pb
et non c'est moins efficace avec le cache. Avant tu chargeais toutes ton etude et tu t'en ressers directement sur toutes les pages. La tu vas devoir faire plusieurs appels

2024-12-11 17:55 UTC, desoindx commented on src/db/study.ts
> +        !allowedUser.user.organizationId || !getAllowedLevels(allowedUser.user.level).includes(study.level)
yes, mais le check du level est util que si il a un niveau. Donc faisable coté front

2024-12-11 17:56 UTC, desoindx requested changes
Commentaire precedent non resolu

2024-12-12 07:52 UTC, desoindx commented
Tu peux verifier le comportement de https://github.com/orgs/ABC-TransitionBasCarbone/projects/3/views/1?pane=issue&itemId=82946378&issue=ABC-TransitionBasCarbone%7Cbilan-carbone%7C34 stp ?

2024-12-12 12:24 UTC, desoindx requested changes

2024-12-12 12:24 UTC, desoindx commented on src/components/study/rights/NewStudyRightDialog.tsx
> +          {otherOrganization && t('otherOrganization')}
```suggestion
          {t('otherOrganization')}
```

2024-12-12 12:24 UTC, desoindx commented on src/components/study/rights/NewStudyRightForm.tsx
> +        rightsWarning={otherOrganization && form.getValues().role !== StudyRole.Reader}
```suggestion
        rightsWarning={form.getValues().role !== StudyRole.Reader}
```

2024-12-12 12:24 UTC, desoindx commented on src/db/study.ts
> +export const getStudyById = async (id: string, organizationId: string | null) => {
il faut pas utiliser l'organization de la study ?

2024-12-12 12:59 UTC, fortinlouis commented on src/db/study.ts
> +export const getStudyById = async (id: string, organizationId: string | null) => {
Justement non : organizationId c'est le filtre pour savoir si j'envoi les données organization et level des users, il faut donc que cela corresponde à l'utilisateur

2024-12-12 13:18 UTC, desoindx commented on src/db/study.ts
> +export const getStudyById = async (id: string, organizationId: string | null) => {
J'ai du mal a voir la difference. Tu as un use case en tete ?

2024-12-12 13:26 UTC, fortinlouis commented on src/db/study.ts
> +export const getStudyById = async (id: string, organizationId: string | null) => {
- Je suis un utilisateur A d'une orga X, je récupère l'étude E1 qui appartient à mon organisation. Parmi les utilisateurs de l'étude, je ne veux récupérer les données confidentielles que des utilisateurs de mon organisation (X)
- Je suis un utilisateur B d'une orga Y, invité sur l'étude E1 qui appartient à l'organisation X. Parmi les utilisateurs de l'étude, je ne veux récupérer les données confidentielles que des utilisateurs de mon organisation (Y)

Selon moi, comme organizationId n'est utilisé que pour le filtre sur allowedUsers, il faut que ça soit celui de l'utilisateur, pas de l'étude. Je pourrais le nommer userOrganizationId, mais je ne suis pas sûr que ça rendrait les choses plus claires

2024-12-12 13:32 UTC, desoindx commented on src/db/study.ts
> +export const getStudyById = async (id: string, organizationId: string | null) => {
ok, j'ai l'impression que le comportement est pas clair dans les deux cas et que ca complique le code.
Mais comme tu le sens

2024-12-12 13:36 UTC, merged