Feat/255 negaoctet import
ABC-TransitionBasCarbone/bilan-carbone pull request #303
Opened 2024-12-19 15:02 UTC by fortinlouis

#255

2024-12-19 16:08 UTC, desoindx requested changes
tu peux renommer import-fe en importEmissionFactor ? 
et harmoniser le camel case de NegaOctet

2024-12-19 16:08 UTC, desoindx commented on src/scripts/baseEmpreinte/getEmissionFactors.ts
> +} from '../../services/import-fe/baseEmpreinte/getEmissionFactors'
Pq ce changement ?

2024-12-19 16:08 UTC, desoindx commented on src/services/import-fe/negaoctet/import.ts
> +export const negaoctetRequiredColumns = requiredColums.concat(['Unité_espagnol'])
pq on a besoin de l'espagnol ?

2024-12-19 16:08 UTC, desoindx commented on src/services/import-fe/negaoctet/import.ts
> +const getUnit = (value?: string): Unit | null => {
pq il y a un getUnit specifique a negaoctet ?

2024-12-19 16:08 UTC, desoindx commented on src/services/import-fe/negaoctet/import.ts
> +  const getUnitFunc = (emissionFactor: NegaoctetEmissionFactor) =>
quel cas n'est pas gere par une seule colonne ?

2024-12-19 16:08 UTC, desoindx commented on src/services/import-fe/negaoctet/getEmissionFactors.ts
>    'CH4f',
Le code est ultra dupliqué...

2024-12-19 16:14 UTC, fortinlouis commented on src/services/import-fe/negaoctet/import.ts
> +export const negaoctetRequiredColumns = requiredColums.concat(['Unité_espagnol'])
Dans le fichier, certaines lignes n'ont pas d'unité en français ni anglais, donc j'ai ajouté l'espagnol

2024-12-19 16:50 UTC, fortinlouis commented on src/services/import-fe/negaoctet/import.ts
> +export const negaoctetRequiredColumns = requiredColums.concat(['Unité_espagnol'])
J'ai rien dit, c'était un décalage dans mon CSV

2024-12-23 12:41 UTC, desoindx requested changes

2024-12-23 12:41 UTC, desoindx commented on src/services/importEmissionFactor/baseEmpreinte/getEmissionFactorsFromAPI.ts
> +        `https://data.ademe.fr/data-fair/api/v1/datasets/base-carboner/lines?select=${requiredColumns.join(',')}&q_fields=Statut_de_l'élément&q=Valide%20générique,Valide%20spécifique,Archivé`
pq tu as enlevé les validStatuses ?

2024-12-23 12:41 UTC, desoindx commented on src/services/importEmissionFactor/getEmissionFactorsFromCSV.ts
> +      const encoding = buffer.includes('\xE9') || buffer.includes('\xE8') ? 'latin1' : 'utf-8'
tu peux mettre un commentaire avec de la doc la dessus ?

2024-12-23 12:41 UTC, desoindx commented on src/services/importEmissionFactor/getEmissionFactorsFromCSV.ts
> +            if (row.Type_Ligne === 'Poste') {
Pq on check plus le status ?

2024-12-23 12:41 UTC, desoindx commented on src/services/importEmissionFactor/import.ts
> +    if (Number(i) % 10 === 0) {
pq ?

2024-12-23 12:41 UTC, desoindx commented on src/services/importEmissionFactor/import.ts
> +      totalCo2: part.Total_poste_non_décomposé,
pq tu as supprimé getGases ?

2024-12-23 12:41 UTC, desoindx commented on src/services/importEmissionFactor/import.ts
> +      delete data.metaData
je comprends pas ce use case, ca devrait etre géré l303 ?

2024-12-23 12:41 UTC, desoindx commented on src/services/importEmissionFactor/import.ts
> +        data.sf6 = part.Valeur_gaz_supplémentaire_2
pb de merge ?

2024-12-23 14:22 UTC, fortinlouis commented on src/services/importEmissionFactor/import.ts
> +        data.sf6 = part.Valeur_gaz_supplémentaire_2
Il y a clairement eu un problème de rebase en effet ...

2024-12-23 17:02 UTC, desoindx requested changes

2024-12-23 17:02 UTC, desoindx commented on src/services/importEmissionFactor/getEmissionFactorsFromCSV.ts
> +       * https://www.w3schools.com/charsets/ref_utf_ebcdic.asp
le lien ne marche pas

2024-12-23 17:02 UTC, desoindx commented on src/services/importEmissionFactor/getEmissionFactorsFromCSV.ts
> -            await cleanImport(transaction, emissionFactorImportVersion.id)
a remettre ?

2024-12-23 18:10 UTC, desoindx approved these changes

2024-12-23 18:10 UTC, desoindx commented on src/services/importEmissionFactor/getEmissionFactorsFromCSV.ts
> +      const encoding = buffer.includes('\xE9') || buffer.includes('\xE8') ? 'latin1' : 'utf-8'
toujours pas tres clair pour moi :/

2024-12-24 08:39 UTC, merged