199 script de batch pour envoyer les utilisateurs du wordpress vers le bc+
ABC-TransitionBasCarbone/bilan-carbone pull request #304
Opened 2024-12-19 15:55 UTC by RomainCrevecoeur

2024-12-20 16:28 UTC, desoindx requested changes

2024-12-20 16:28 UTC, desoindx commented on prisma/seed.ts
> +  await Promise.all([actualities(), licenses(), users(), reCreateBegesRules(), getUsersFromFTP()])
Pas sur qu'on veuille recuperer ca dans les seeds (jouer dans les tests e2e)

2024-12-20 16:28 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +const prisma = new PrismaClient()
tu peux utiliser le prisma client par defaut ?

2024-12-20 16:28 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +class MyWritableStream extends Writable {
pq une class ?

2024-12-20 16:28 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +  client.ftp.verbose = true
on veut que ce soit verbeux tout le temps ?

2024-12-20 16:28 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +      port: parseInt(process.env.NEXT_FTP_PORT || '22', 10),
tu peux rajouter ces variables dans le .env.dist avec des <secret> pour les données privées ? qu'on sache qu'elles sont a remplir

2024-12-20 16:28 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +      await prisma.user.create({
utiliser un createMany

2024-12-20 16:28 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +          isActive: false,
faut qu'ils soient isValidated à false aussi 
et la ils n'ont pas d'orga ?

2024-12-24 08:36 UTC, RomainCrevecoeur commented on src/services/ftpUsers/getUsers.ts
> +class MyWritableStream extends Writable {
Est ce que tu as une manière différente de faire un extend de la méthode _write?

2024-12-24 09:09 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +class MyWritableStream extends Writable {
on('data') puis on('end') ?

2024-12-24 11:12 UTC, desoindx requested changes

2024-12-24 11:12 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +      // Insert data into PostgreSQL using Prisma
commentaire inutlie ?

2024-12-24 11:12 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +        .filter((data) => data.length > 1) // Adjust based on your file format
il y a quoi a ajusté ?

2024-12-24 11:12 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +        .map((line) => line.split(','))
tu peux utiliser un vrai parser csv ? la il va y avoir des soucis des qu'on a un " par exemple

2024-12-24 11:12 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +      users.shift()
ca fait quoi ce shift ?

2024-12-24 11:12 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +          lastName: value[0],
toutes les memes valeurs ?

2024-12-24 11:17 UTC, RomainCrevecoeur commented on src/services/ftpUsers/getUsers.ts
> +        .filter((data) => data.length > 1) // Adjust based on your file format
Cela supprime une ligne vide prise en compte à la fin du CSV

2024-12-24 11:17 UTC, RomainCrevecoeur commented on src/services/ftpUsers/getUsers.ts
> +      users.shift()
Cela supprime la ligne d'entête du CSV

2024-12-24 11:18 UTC, RomainCrevecoeur commented on src/services/ftpUsers/getUsers.ts
> +          lastName: value[0],
Oui pour l'instant je n'ai pas le fichier cible que va me fournir Almarena

2024-12-24 13:18 UTC, desoindx commented on src/services/ftpUsers/getUsers.ts
> +        .filter((data) => data.length > 1) // Adjust based on your file format
tu peux mettre un commentaire qui explique ca ?

2025-01-02 09:24 UTC, merged