update study sites
ABC-TransitionBasCarbone/bilan-carbone pull request #333
Opened 2024-12-24 14:46 UTC by fortinlouis

#265

2024-12-26 10:55 UTC, desoindx requested changes
Il manque le use case ou des sources d'emissions ont été crées pour un site que l'on supprime

2024-12-26 10:55 UTC, desoindx commented on src/app/(dashboard)/etudes/[id]/(organization)/perimetre/modifier/page.tsx
> +import EditStudyPerimeterPage from '@/components/pages/EditStudyPerimeter'
On ne veut pas de nouvelle page pour ca

2024-12-26 10:55 UTC, desoindx commented on src/components/organization/Sites.module.css
> +
bizarre, quel est le probleme ?

2024-12-26 10:55 UTC, desoindx commented on src/components/organization/Sites.tsx
> +        <caption>
pas sur que ce soit un caption qu'on veut
un caption est fait pour decrire une table, la tu rajoutes un bouton qui n'a rien a faire ici

2024-12-26 10:55 UTC, desoindx commented on src/components/study/edit/EditStudySitesForm.tsx
> +        const studySite = study.sites.find((ss) => ss.site.id === site.id)
ss a renommer

2024-12-26 10:55 UTC, desoindx commented on src/components/study/edit/EditStudySitesForm.tsx
> +  const siteList =
dasn un useMemo ?

2024-12-26 10:55 UTC, desoindx commented on src/components/study/organization/Select.tsx
> +
effectivement c'est pas ouf
Qu'est ce qui t'empeche d'avoir un seul form ?

2024-12-26 10:55 UTC, desoindx commented on src/db/study.ts
> +export const updateStudySites = (studyId: string, newStudySites: Prisma.StudySiteCreateManyInput[]) => {
c'est pas un update du coup
recreate ?

2024-12-26 10:55 UTC, desoindx commented on src/i18n/en.json
> +      "title": "Permiter on study : {name}",
```suggestion
      "title": "Permiter on study: {name}",
```

2024-12-27 09:00 UTC, fortinlouis commented on src/components/study/organization/Select.tsx
> +
Si j'utilise form qui est de type UseFormReturn<CreateStudyCommand>, j'obtiens cette erreur :
```
 Type '{ organizationId: string; sites: { id: string; selected: boolean; etp?: number | undefined; ca?: number | undefined; }[]; }' is missing the following properties from type '{ organizationId: string; level: "Initial" | "Standard" | "Advanced"; name: string; sites: { id: string; selected: boolean; etp?: number | undefined; ca?: number | undefined; }[]; validator: string; startDate: string; endDate: string; isPublic: string; exports: { ...; }; }': level, name, validator, startDate, and 3 more.ts(2322)
```

2024-12-27 09:03 UTC, desoindx commented on src/components/study/organization/Select.tsx
> +
parceque tu fais l'union de ton Sites sans inclure le form initial ?

2025-01-08 11:54 UTC, RomainCrevecoeur commented on src/components/study/organization/Select.tsx
> +
J'ai l'impression que si tu fais <Sites form={form as UseFormReturn<SitesCommand>} sites={sites} /> ça fonctionne @fortinlouis ?

2025-01-13 10:35 UTC, desoindx requested changes

2025-01-13 10:35 UTC, desoindx commented on src/components/organization/Sites.tsx
> +  withSelection: boolean
c'est une bonne pratique en react de mettre les boolean en optionnel

2025-01-13 10:35 UTC, desoindx commented on src/components/organization/edit/EditOrganizationForm.tsx
> +      <Sites form={form as unknown as UseFormReturn<SitesCommand>} sites={sites} withSelection={false} />
ouch...

2025-01-13 10:35 UTC, desoindx commented on src/components/study/perimeter/StudyPerimeter.tsx
> +  }, [siteList, isEditing])
c'est bizarre ce code, tu as deux trucs qui font la même chose (siteList et les sites du form). Quel est l'interet ?

2025-01-13 10:35 UTC, desoindx commented on src/components/study/perimeter/StudyPerimeter.tsx
> +    const existingSiteIds = study.sites.map((studySite) => studySite.site.id)
ca devrait etre fait coté serveur ce "existing site id"

2025-01-13 10:35 UTC, desoindx commented on src/db/study.ts
> +      await transaction.studyEmissionSource.deleteMany({ where: { studyId, siteId: { in: deletedSiteIds } } })
tu peux pas le faire en une fois ?

2025-01-13 10:35 UTC, desoindx commented on src/db/study.ts
> +        const where = { studyId, siteId: studySite.siteId }
pq cest constante ? et pq pas un map ?

2025-01-13 10:35 UTC, desoindx commented on src/db/study.ts
> +        promises.push(transaction.studySite.updateMany({ where, data }))
au lieu de faire un create et un update, tu peux pas faire un upsert ?

2025-01-13 10:35 UTC, desoindx commented on src/services/serverFunctions/study.command.ts
> +export type SitesCommand = z.infer<typeof SitesCommandValidation>
Duplication avec celui du dessus ?

2025-01-13 10:35 UTC, desoindx commented on src/components/study/perimeter/StudyPerimeter.tsx
> +    const hasActivityData = await Promise.all(
C'est a faire coté serveur ca non ? le client n'a pas l'info ?

2025-01-13 10:35 UTC, desoindx commented on src/services/serverFunctions/study.ts
> +  const study = await getStudyById(studyId, organizationId)
tu vas loader un paquet de fois la meme study ici ? vu que c'est fait pour chaque site

2025-01-13 10:35 UTC, desoindx commented on src/services/serverFunctions/study.ts
> +      ) as OrganizationWithSites['sites'][0]
pq il faut le typer explicitement ici ?

2025-01-13 14:14 UTC, fortinlouis commented on src/services/serverFunctions/study.command.ts
> +export type SitesCommand = z.infer<typeof SitesCommandValidation>
ChangeStudySitesCommand a un attribut organizationId, que SitesCommand n'a pas

SitesCommand a un site.name qui n'est pas présent dans l'autre

2025-01-13 14:26 UTC, fortinlouis commented on src/services/serverFunctions/study.ts
> +      ) as OrganizationWithSites['sites'][0]
Comme pour la création : le find peut ne rien retourner donc on forcer le type pour éviter un `undefined`. J'ai ajouter aux 2 un filtre pour supprimer ces valeurs non définies (qui ne sont pas censée arriver)

2025-01-15 09:49 UTC, desoindx approved these changes

2025-01-15 16:27 UTC, desoindx requested changes

2025-01-15 16:27 UTC, desoindx commented on .github/workflows/ci.yml
> +          path: /home/runner/work/bilan-carbone/bilan-carbone/cypress/screenshots
Tu peux faire ca dans un commit separe stp ? ca a rien a voir avec.

2025-01-16 08:04 UTC, desoindx approved these changes

2025-01-16 08:10 UTC, merged