chore: Review session management
ABC-TransitionBasCarbone/bilan-carbone pull request #345
Opened 2024-12-27 08:17 UTC by desoindx

2024-12-31 07:18 UTC, cmolle requested changes

2024-12-31 07:18 UTC, cmolle commented on src/components/hoc/withStudy.tsx
> +  const Component = async (props: any & Props & UserProps) => {
Pour éviter d'avoir à supprimer la règle any sur tout le fichier (idem pour withAuth), est-ce qu'on ne pourrait pas : 
- soit de définir un type assez large (je suppose que tous les props seront sous la forme d'un objet clé, valeur ?) 
- soit désactiver uniquement pour cette ligne

2024-12-31 07:18 UTC, cmolle commented on src/components/hoc/withAuth.tsx
> +      return <NotFound />
S'il n'y a pas de session, est-ce qu'il ne faudrait pas plutôt renvoyer vers la page de login ?

2024-12-31 07:18 UTC, cmolle commented on src/app/(dashboard)/etudes/[id]/(organization)/perimetre/page.tsx
> -  }
Cette partie là n'est pas dans withStudy

2024-12-31 07:18 UTC, cmolle commented on src/app/(dashboard)/etudes/[id]/(organization)/page.tsx
> +    if (!(await canReadStudy(props.user, study))) {
Pourquoi ne pas utiliser useStudy ? (attention il n'y a pas encore canReadStudyDetails dans useStudy)

2024-12-31 07:18 UTC, cmolle commented on src/app/(dashboard)/etudes/[id]/(organization)/comptabilisation/saisie-des-donnees/page.tsx
> +export default withAuth(DataEntry)
Même question, on pourrait utiliser useStudy ?

2024-12-31 07:18 UTC, cmolle commented on src/app/(dashboard)/etudes/[id]/(organization)/comptabilisation/resultats/page.tsx
> -  }
idem

2024-12-31 07:18 UTC, cmolle commented on src/app/(dashboard)/etudes/[id]/(organization)/cadrage/page.tsx
> -  if (!(await canReadStudyDetail(session.user, study))) {
idem

2024-12-31 07:18 UTC, cmolle commented on src/app/(dashboard)/etudes/[id]/(organization)/cadrage/ajouter/page.tsx
> -    return <NotFound />
idem

2024-12-31 07:18 UTC, cmolle commented on src/app/(dashboard)/etudes/[id]/(organization)/cadrage/ajouter-contributeur/page.tsx
> -    return <NotFound />
idem

2024-12-31 07:18 UTC, cmolle commented on src/app/(dashboard)/etudes/[id]/(contributor)/contributeur/page.tsx
>    }
Pourquoi ne pas utiliser useStudy ?

2024-12-31 07:18 UTC, cmolle commented on src/app/(dashboard)/admin/page.tsx
> +export default withAuth(Admin)
Je sais que ce n'est pas lié à ta PR, mais il faudrait peut être appeler cette page superAdmin non ? Vu qu'on a aussi un rôle admin ca peut porter à confusion d'avoir une page non accessible aux admins mais appelée comme ca.

2025-01-06 15:34 UTC, fortinlouis commented on src/app/(dashboard)/etudes/[id]/(organization)/page.tsx
> +const StudyView = async (props: Props & UserProps) => {
étendre UserProps à la déclaration de l'interface Props

2025-01-06 15:34 UTC, fortinlouis commented on src/app/(dashboard)/etudes/[id]/(organization)/comptabilisation/saisie-des-donnees/[post]/page.tsx
>  interface Props {
```suggestion
interface Props extends StudyProps, UserProps {
```

2025-01-06 15:34 UTC, fortinlouis commented on src/app/(dashboard)/etudes/[id]/(organization)/comptabilisation/resultats/page.tsx
> +const ResultatsPages = async (props: StudyProps & UserProps) => {
const ResultsPages = async ({ study }: StudyProps) => {

2025-01-06 15:34 UTC, fortinlouis commented on src/components/hoc/withStudy.tsx
> +  const Component = async (props: any & Props & UserProps) => {
Personnellement, je trouve que désactiver sur une ligne ou un fichier entier, dans ce fichier cela ne change rien (utilisé une seule fois). Et pour le type assez large, je me demande si ce n'est pas se compliquer beaucoup la vie pour un gain marginal

2025-01-06 16:04 UTC, cmolle commented on src/components/hoc/withStudy.tsx
> +  const Component = async (props: any & Props & UserProps) => {
Le fait de désactiver sur une seul ligne ca permet d'éviter d'ajouter des any sur d'autres lignes sans s'en rendre compte. Qu'en penses tu ? 

Ok pour le type plus large

2025-01-06 16:05 UTC, cmolle commented on src/components/hoc/withAuth.tsx
> +      return <NotFound />
Je ne suis pas sûre de comprendre, preneuse pour qu'on s'appelle

2025-01-07 08:02 UTC, cmolle commented on src/app/(dashboard)/etudes/[id]/(organization)/perimetre/page.tsx
> -  }
Oui mais il faut quand même continuer de tester ce cas dans ce composant. J'ai créé un nouveau composant du coup pour avoir plus de cas posisble

2025-01-07 08:05 UTC, cmolle commented on src/app/(dashboard)/organisations/[id]/modifier/page.tsx
>  interface Props {
C'est une meilleure pratique que le & ?

2025-01-07 08:15 UTC, cmolle commented on src/app/(dashboard)/etudes/[id]/(organization)/perimetre/page.tsx
> -  }
Je comprends pas la différence entre canReadStudy et canREadStudyDetails ? Les deux ont l'air de faire les même check : vérification que l'étude est en public et que la personne est dans l'entreprise ou vérification que l'utilisateur est inclus dans les personne ayant accès à l'étude

2025-01-07 08:44 UTC, cmolle commented on src/components/hoc/withAuth.tsx
> +      return <NotFound />
@desoindx pourrais-tu nous dire pourquoi tu as choisi un notFound plutôt qu'une redirection ? On voit des avantages/inconvenients dans les deux cas avec Louis et on voudrait ton avis :)

2025-01-07 09:25 UTC, cmolle commented on src/app/(dashboard)/organisations/[id]/modifier/page.tsx
>  interface Props {
Vu ensemble : finalement on laisse comme ca

2025-01-07 09:26 UTC, cmolle commented on src/app/(dashboard)/etudes/[id]/(organization)/perimetre/page.tsx
> -  }
Vu ensemble : la différence est seulement sur les contributeurs

2025-01-08 09:30 UTC, fortinlouis commented on src/components/hoc/withStudyNotContributor.tsx
> +const withStudyNotContributor = (WrappedComponent: React.ComponentType<any & UserProps & StudyProps>) => {
```suggestion
const withStudyDetails = (WrappedComponent: React.ComponentType<any & UserProps & StudyProps>) => {
```

2025-01-08 09:30 UTC, fortinlouis commented on src/services/permissions/study.ts
> -  if (study.isPublic) {
Pourquoi cette suppression ?

2025-01-08 10:00 UTC, cmolle commented on src/services/permissions/study.ts
> -  if (study.isPublic) {
C'est ce dont on parlait hier, cette vérification est déjà dans canReadStudy donc pas besoin de l'avoir deux fois

2025-01-08 16:04 UTC, fortinlouis requested changes

2025-01-08 16:04 UTC, fortinlouis commented on src/components/hoc/withStudyDetails.tsx
> +const withStudyNotContributor = (WrappedComponent: React.ComponentType<any & UserProps & StudyProps>) => {
```suggestion
const withStudyDetails = (WrappedComponent: React.ComponentType<any & UserProps & StudyProps>) => {
```

2025-01-08 16:52 UTC, cmolle commented on src/components/hoc/withStudyDetails.tsx
> +const withStudyNotContributor = (WrappedComponent: React.ComponentType<any & UserProps & StudyProps>) => {
Trop bizarre, j'ai du checkout le fichier sans faire expres, je corrige

2025-01-08 16:55 UTC, cmolle approved these changes

2025-01-09 09:41 UTC, fortinlouis approved these changes

2025-01-09 10:20 UTC, merged