chore: cache FE
ABC-TransitionBasCarbone/bilan-carbone pull request #350
Opened 2024-12-27 12:07 UTC by desoindx

2024-12-29 13:02 UTC, fortinlouis commented on src/db/emissionFactors.ts
> +const getCachedDefaultEmissionFactors = unstable_cache(() => {
```suggestion
const getCachedDefaultEmissionFactors = unstable_cache(getDefaultEmissionFactors)
```

2024-12-31 07:26 UTC, cmolle requested changes

2024-12-31 07:26 UTC, cmolle commented on .env.dist
> +NO_CACHE=true
Tu pourrais ajouter une ligne à la fin du fichier ?

2024-12-31 07:26 UTC, cmolle commented on src/db/emissionFactors.ts
> +    orderBy: { createdAt: 'desc' },
Est-ce qu'on peut trier par ordre alphabétique plutôt par défaut ?

2024-12-31 07:26 UTC, cmolle commented on src/db/emissionFactors.ts
> +import { unstable_cache } from 'next/cache'
J'ai l'impression que c'est une méthode qui n'est pas conseillée : https://nextjs.org/docs/app/api-reference/functions/unstable_cache

2024-12-31 07:29 UTC, cmolle commented
>  Server has to be restart when manually uploading FE


Cela veut dire que tu es parti sur la solution simple et que pour invalider le cache il faut relancer le serveur ? (par rapport à ce qui est écrit dans le ticket). 
Qu'est-ce qui t'a fait choisir ce cas plutôt qu'un autre ? 
Que penses-tu de prévoir quelque chose pour ne pas qu'on oublie ? (par exemple via un message dans la console quand on télécharge des FEs, des commentaires dans le code...)

2025-01-13 12:35 UTC, desoindx commented on src/db/emissionFactors.ts
> +import { unstable_cache } from 'next/cache'
Vu ensemble, la nouvelle function n'est dispo que en version canary de next. On laisse comme ca pour l'instant

2025-01-13 13:00 UTC, merged