feat: add CR and multiple organizations
ABC-TransitionBasCarbone/bilan-carbone pull request #39
Opened 2024-10-14 10:10 UTC by desoindx

link #10

2024-10-15 09:10 UTC, fortinlouis commented on src/components/study/organization/select/index.tsx
> +import React, { useMemo, useState } from 'react'
L'import de React n'est pas necessaire

2024-10-15 09:11 UTC, fortinlouis commented on src/components/study/organization/select/index.tsx
> +        <>
On peut directement mettre le Select

2024-10-15 09:43 UTC, desoindx commented on src/components/study/organization/select/index.tsx
> +import React, { useMemo, useState } from 'react'
a gerer avec une regle de linter

2024-10-15 09:44 UTC, desoindx commented on src/components/study/organization/select/index.tsx
> +        <>
pq ? si il y a un element c'est informatif (notamment pour les utilisateurs qui n'ont qu'une organisation et qui ne peuvent pas en creer)

2024-10-15 09:44 UTC, desoindx commented on src/i18n/fr.json
> +}
yes, l'anglais je le ferai quand ca sera un peu plus stable 
fin de fichier a gerer avec le linter

2024-10-15 10:19 UTC, fortinlouis commented on src/components/study/organization/select/index.tsx
> +        <>
Pardon, je voulais dire qu'on pouvait virer la balise <> qui wrappe le Select

2024-10-16 08:31 UTC, fortinlouis requested changes

2024-10-16 08:31 UTC, fortinlouis commented on src/app/etudes/creer/page.tsx
Il ne faut pas mettre ce dossier dans (dashboard) ?

2024-10-16 08:31 UTC, fortinlouis commented on src/app/etudes/creer/page.tsx
Egalement, il n'y a pas de lien pour accéder à cette page

2024-10-16 08:31 UTC, fortinlouis commented on src/app/etudes/creer/page.tsx
Et, dans la même veine, je dirais qu'il faut mettre la page logout dans (public). Même si elle n'affiche rien et sert juste à se déconnecter, je pense qu'il vaut mieux harmoniser

2024-10-16 08:46 UTC, fortinlouis approved these changes

2024-10-16 08:57 UTC, merged