Feat/8 mentions
ABC-TransitionBasCarbone/bilan-carbone pull request #48
Opened 2024-10-16 11:41 UTC by fortinlouis

https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/8

2024-10-16 13:23 UTC, desoindx requested changes

2024-10-16 13:23 UTC, desoindx commented on src/app/(dashboard)/mentions-legales/page.tsx
> +const contactMail = 'contact@associationbilancarbone.fr'
pq des constantes pour ca ? si c'est facilement modifiable il vaudrait mieux utiliser des variables d'env ?

2024-10-16 13:23 UTC, desoindx commented on src/app/(dashboard)/mentions-legales/page.tsx
> +        pourra être apportée. Un lien devra être établi vers l’Association pour la transition Bas Carbone.{' '}
extra space 
```suggestion
        pourra être apportée. Un lien devra être établi vers l’Association pour la transition Bas Carbone.
```

2024-10-16 13:23 UTC, desoindx commented on src/app/(dashboard)/mentions-legales/styles.module.css
> +  h1 {
est ce qu'on ferait pas un css globale pour les titres ?

2024-10-16 13:23 UTC, desoindx commented on src/app/(dashboard)/styles.module.css
> +  margin-top: 4rem; /* navbar height */
Ca va etre un sacré bordel ! La taille de la nav bar va changer a mort

2024-10-16 13:23 UTC, desoindx commented on src/app/(dashboard)/styles.module.css
> +  overflow-y: auto;
pq ?

2024-10-16 13:23 UTC, desoindx commented on src/components/navbar/styles.module.css
> +  width: calc(100% - 1rem);
pq ?

2024-10-16 13:23 UTC, desoindx commented on src/components/navbar/styles.module.css
> +  position: fixed;
Pas sur qu'on veuille une nav bar fixe ?

2024-10-16 13:23 UTC, desoindx commented on src/components/navbar/styles.module.css
> +  z-index: 1000;
random number

2024-10-16 13:23 UTC, desoindx commented on src/css/var.css
> +.mb1 {
les namings sont pas consistents

2024-10-16 13:23 UTC, desoindx commented on src/tests/end-to-end/app/legal-notices.cy.ts
> +    cy.get('[data-testid="input-email"] > .MuiInputBase-input').should('be.visible').type('bc-test-user-1@yopmail.com')
Ca serait cool de faire un helper pour le login

2024-10-16 13:23 UTC, desoindx commented on src/tests/end-to-end/app/legal-notices.cy.ts
> +  describe('Access', () => {
useless describe

2024-10-16 13:23 UTC, desoindx commented on src/tests/end-to-end/app/legal-notices.cy.ts
> +    it('Displays the body of the legal notices', () => {
manque un should ?

2024-10-16 13:23 UTC, desoindx commented on src/tests/end-to-end/app/legal-notices.cy.ts
> +      cy.get('[data-testid="legal-notices"]').should('be.visible')
sert pas a grand chose ce test

2024-10-16 13:23 UTC, desoindx commented on src/tests/end-to-end/app/legal-notices.cy.ts
> +      cy.get('[data-testid="legal-notices"]').should('be.visible')
(les e2e sont assez long a setup, je pense que tout ce qu'il y a en dessous peut etre un seul test)

2024-10-16 13:34 UTC, fortinlouis commented on src/app/(dashboard)/mentions-legales/styles.module.css
> +  h1 {
J'ai changé pour des <div className="section">. Mais oui, c'est une idée

2024-10-16 13:36 UTC, fortinlouis commented on src/app/(dashboard)/styles.module.css
> +  margin-top: 4rem; /* navbar height */
Pouquoi ? la taille de la navbar est fixe à 4rem

2024-10-16 13:37 UTC, fortinlouis commented on src/app/(dashboard)/styles.module.css
> +  overflow-y: auto;
J'ai pris le parti pris d'afficher la navbar en continue. En partant de ce postulat, l'app entière prend toute la page et content doit scroller

2024-10-16 13:39 UTC, fortinlouis commented on src/components/navbar/styles.module.css
> +  width: calc(100% - 1rem);
pour prendre en compte le padding

2024-10-16 13:39 UTC, fortinlouis commented on src/components/navbar/styles.module.css
> +  position: fixed;
C'est effectivement un parti pris de ma part

2024-10-16 13:41 UTC, fortinlouis commented on src/css/var.css
> +.mb1 {
Justement si : le - de "p-2" veut dire division. Là où le chiffre collé veut dire multiplication. En effet, pour le 1 c'est équivalent

2024-10-16 13:52 UTC, fortinlouis commented on src/tests/end-to-end/app/legal-notices.cy.ts
> +      cy.get('[data-testid="legal-notices"]').should('be.visible')
Je suis d'accord pour regrouper les tests. En revanche, pour moi tester le rendu avec le layout global, avant de s'attaquer au contenu est une bonne pratique

2024-10-16 15:29 UTC, desoindx requested changes

2024-10-16 15:29 UTC, desoindx commented on src/app/(dashboard)/styles.module.css
> +  margin-top: 4rem; /* navbar height */
la taille va bouger des qu'on va rajouter genre un logo, ou qu'on va faire du responsive
ca se fait plus trop dans le web les navbar fix, tu veux pas la mettre normal et eviter de se prendre la tete ?

2024-10-16 15:29 UTC, desoindx commented on src/components/navbar/Navbar.module.css
> +  width: calc(100% - 1rem);
ok j'ai compris,
tu peux faire un container qui prend 100% ? et gerer le padding dans l'enfant ?

2024-10-17 07:57 UTC, fortinlouis commented
Gabriel demande à ce qu'on garde la navbar fixe : https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/7#issuecomment-2418812541

Je propose qu'on avance et qu'on avisera si cela nous pose problème par la suite

2024-10-17 08:13 UTC, desoindx approved these changes

2024-10-17 08:13 UTC, desoindx commented on src/tests/end-to-end/app/legal-notices.cy.ts
> +    cy.login('bc-test-user-1@yopmail.com', 'password-1')
nitpick: valeur par defaut, inutile de les preciser

2024-10-17 08:27 UTC, merged