Feat/6 welcome page
ABC-TransitionBasCarbone/bilan-carbone pull request #54
Opened 2024-10-17 15:08 UTC by fortinlouis

https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/6

2024-10-17 15:33 UTC, desoindx requested changes

2024-10-17 15:33 UTC, desoindx commented on docker-compose.yml
> +    restart: unless-stopped
pq ?

2024-10-17 15:33 UTC, desoindx commented on prisma/legacy_data/actualities.ts
> +export const ACTUALITIES = [
why ? ca peut etre inserer directement en base de prod ?

2024-10-17 15:33 UTC, desoindx commented on src/app/(dashboard)/styles.module.css
> +  @media screen and (max-width: 1000px) {
utilisé des rem

2024-10-17 15:33 UTC, desoindx commented on src/components/actuality/Actualities.tsx
> +      {actualities.length === 0 ? <>{t('no-item')}</> : sortedActualities.map(ActualityRow)}
je suis pas fan de cet ecriture, ca force la clé dans le composant enfant, alors que c'est au parent de la definir (tu peux utiliser une ActualityRow dans plein d'autres contexte)

2024-10-17 15:33 UTC, desoindx commented on src/components/actuality/Actuality.tsx
> +    <div className={classNames(styles.header, 'flex mb-2')}>
utiliser des p au lieu de div, c'est du text

2024-10-17 15:33 UTC, desoindx commented on src/components/actuality/styles.module.css
> +.actuality {
pq cette imbrication ?

2024-10-17 15:33 UTC, desoindx commented on src/components/navbar/Study.tsx
> +  return <Button>{t('title')}</Button>
Why ?

2024-10-17 15:33 UTC, desoindx commented on src/components/study/Study.module.css
StudyContainer.module.css

2024-10-17 15:33 UTC, desoindx commented on src/components/study/StudyContainer.tsx
> +    <div data-testid="home-studies" className="flex-col box grow m-2">
box marche pas ici ?

2024-10-17 15:33 UTC, desoindx commented on src/components/study/results/styles.module.css
ResultsContainer.module.css

2024-10-17 15:33 UTC, desoindx commented on src/components/study/results/styles.module.css
> +  > div {
utiliser une vraie class

2024-10-17 15:33 UTC, desoindx commented on src/css/globals.css
> +
je comprends pas l'interet du css la ? pq pas un vrai composant react Box avec des children ?

2024-10-17 15:35 UTC, fortinlouis commented on docker-compose.yml
> +    restart: unless-stopped
Pourquoi pas ? Avoir le container qui se lance automatiquement c'est pas enviable ?

2024-10-17 15:36 UTC, fortinlouis commented on prisma/legacy_data/actualities.ts
> +export const ACTUALITIES = [
J'ai littéralement repris les données qui sont sur l'appli existante

2024-10-17 15:39 UTC, desoindx commented on prisma/legacy_data/actualities.ts
> +export const ACTUALITIES = [
justement, c'est des données de prod, pas de seed

2024-10-17 15:42 UTC, fortinlouis commented on src/components/navbar/Study.tsx
> +  return <Button>{t('title')}</Button>
Parce que ça n'était pas le but de ce bouton dans la navbar (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/7). À la place, la liste des études est affichée dans la page d'accueil (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/6)

2024-10-17 15:44 UTC, fortinlouis commented on src/components/study/StudyContainer.tsx
> +    <div data-testid="home-studies" className="flex-col box grow m-2">
Comment ça ?

2024-10-17 15:44 UTC, desoindx commented on src/components/actuality/Actualities.tsx
> +    <div data-testid="home-actualities" className="grow box m-2">
Attention, ce genre de marge desaligne les infos => 
![image](https://github.com/user-attachments/assets/61228214-5daf-41a1-a17f-5ab98dbddbee)

2024-10-17 15:44 UTC, desoindx commented on src/components/navbar/Study.tsx
> +  return <Button>{t('title')}</Button>
il sert a quoi ce bouton du coup ?

2024-10-17 15:46 UTC, desoindx commented on src/components/study/StudyContainer.tsx
> +    <div data-testid="home-studies" className="flex-col box grow m-2">
tu as crée un .box dnas le css module correspondant a ce fichier

2024-10-17 16:01 UTC, fortinlouis commented on src/components/navbar/Study.tsx
> +  return <Button>{t('title')}</Button>
`Le bouton "Étude" doit apparaitre sur le bandeau dès lors que l'utilisateur est au sein d'une étude. Hovering sur le bouton "étude" fait apparaitre l'ensemble des fonctionnalités associées à l'étude qui redirigent vers les pages associées`

2024-10-18 08:29 UTC, desoindx requested changes

2024-10-18 08:29 UTC, desoindx commented on src/components/actuality/Actualities.tsx
> +        sortedActualities.map((a) => <ActualityRow key={a.id} actuality={a} />)
```suggestion
        sortedActualities.map((actuality) => <ActualityRow key={actuality.id} actuality={actuality} />)
```

2024-10-18 08:29 UTC, desoindx commented on src/components/actuality/Actuality.tsx
> +  // key: string
to remove

2024-10-18 08:29 UTC, desoindx commented on src/components/actuality/Actuality.tsx
> +    <span className={styles.text}>{actuality.text}</span>
ca aussi c'est du text => dans un p :)

2024-10-18 08:29 UTC, desoindx commented on src/components/base/Box.tsx
> +const Box = ({ children, className, ...rest }: Props) => {
C'est quoi le rest ?

2024-10-18 08:29 UTC, desoindx commented on src/components/navbar/Study.tsx
> +  return <Button>{t('title')}</Button>
ouais... ca va vite sauter ca :)

2024-10-20 18:11 UTC, fortinlouis commented on src/components/base/Box.tsx
> +const Box = ({ children, className, ...rest }: Props) => {
data-testid par exemple

2024-10-20 18:13 UTC, fortinlouis commented on src/components/navbar/Study.tsx
> +  return <Button>{t('title')}</Button>
C'est possible !

2024-10-21 14:47 UTC, desoindx commented on src/components/base/Box.tsx
> +const Box = ({ children, className, ...rest }: Props) => {
Si il est pas dans ton type ça va pas marcher...

2024-10-21 14:57 UTC, fortinlouis commented on src/components/base/Box.tsx
> +const Box = ({ children, className, ...rest }: Props) => {
Moi je constate que si

![image](https://github.com/user-attachments/assets/07edd861-f3a4-4f6e-8a8f-5f8e9c8faecc)

Tu veux que j'ajoute un extends HTMLAttributes<HTMLDivElement> dans les Props de Box ?

2024-10-21 15:53 UTC, desoindx commented on src/components/base/Box.tsx
> +const Box = ({ children, className, ...rest }: Props) => {
nice ! Je savais pas du tout que tu pouvais ajouter des props non typée :) tu sais comment ca marhce ? 
je veux bien oui, mais selon si c'est natif ou pas pas obligatoire

2024-10-21 19:33 UTC, desoindx approved these changes

2024-10-22 06:48 UTC, merged